{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "11077e14",
   "metadata": {},
   "outputs": [],
   "source": [
    "from deepface import DeepFace\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "88867736",
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mUnable to start Kernel 'Facial (Python 3.12.3)' due to a timeout waiting for the ports to get used. \n",
      "\u001b[1;31mView Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "result = DeepFace.verify(img1_path = \"https://imgs.search.brave.com/qdS0yWbwB4ZB1W8uiWHEI5XgqliWJIbplgeBIJaXOaE/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXJjYXZlLmNv/bS93cC93cDY2NDk5/NzAuanBn\", img2_path = \"https://imgs.search.brave.com/BdpRbqbpsDm-zKqheK1G03G7d_xa4ZXSVQgZAJhsMys/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXJzLmNvbS9p/bWFnZXMvaGQvYWxs/dS1hcmp1bi1iaXRp/bmctbmVja2xhY2Ut/em9oOTEyZHNsMnl0/MnIyZC5qcGc\")\n",
    "print(result)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Facial",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
